version: '3.9'

services:
  # Frontend service
  frontend:
    build:
      context: frontend
      dockerfile: ./Dockerfile
    image: frontend
    environment:
      NODE_ENV: development
    ports:
      - "5173:5173"       # Frontend app port
    networks:
      - app-network

  # Backend service
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      args:
        - configuration=Debug
    image: backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal,1433;Database=RecipeDB;User Id=sa;Password=Password12345!;TrustServerCertificate=True;
    ports:
      - "5146:5146"
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    depends_on:
      - db
    networks:
      - app-network

  # Database service
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Password12345!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
